FROM centos:7
MAINTAINER Alex Szczuczko <aszczucz@redhat.com>
EXPOSE 7331

RUN yum install -y epel-release scl-utils https://www.softwarecollections.org/en/scls/rhscl/rh-python34/epel-7-x86_64/download/rhscl-rh-python34-epel-7-x86_64.noarch.rpm && \
    yum install -y bsdtar rh-python34 python-pip libyaml-devel "@Development Tools" java-1.8.0-openjdk && \
    pip install vex && \
    useradd -rm repour && \
    yum install -y curl-devel expat-devel gettext-devel openssl-devel zlib-devel perl-ExtUtils-MakeMaker && \
    curl -o git.tar.gz 'https://www.kernel.org/pub/software/scm/git/git-2.4.4.tar.gz' && \
    tar -xf git.tar.gz && \
    (cd git-2.4.4 && make prefix=/usr/local all && make prefix=/usr/local install) && \
    yum clean all

USER repour
WORKDIR /home/repour
ENTRYPOINT ["/bin/scl", "enable", "rh-python34", "--", "/bin/vex", "rpo", "python", "-m", "repour"]
CMD ["run"]

ADD ["content.tar", "/home/repour/"]

RUN scl enable rh-python34 -- vex -m --python python3.4 rpo pip install -r venv-freeze.txt
